<div class="wrap">
    <h2><?php _e('NC State Branding Bar', 'ncstate-branding-bar'); ?></h2>
    <p>
        The NC State branding bar offers a simple way to connect thousands of
        NC State sites and let users know where they are at all times. This
        element must appear at the top (centered or left-aligned) of all
        official NC State Web sites and pages. No content of any kind may appear
        above this bar. The branding bar is available in various color
        combinations consistent with official university colors.
    </p>
    <p>
        For more information, visit 
        <a href="http://www.ncsu.edu/brand/utility-bar/iframe/config/" target="_blank">http://www.ncsu.edu/brand/utility-bar/iframe/config/</a>.
    </p>
</div>

    <form method="post" action="admin-post.php">
    <?php wp_nonce_field('ncstate-branding-bar'); ?>

    <table class="form-table">
        <tr valign="top">
            <td width="150">
                <label for="nbb_display"><?php _e('Display Branding Bar?', 'ncstate-branding-bar'); ?></label>
            </td>
            <td>
                <select id="nbb_display" name="nbb_display">
                    <option value="1" <?php selected((int)$this->_display, 1); ?>><?php _e('Yes', 'ncstate-branding-bar'); ?></option>
                    <option value="0" <?php selected((int)$this->_display, 0); ?>><?php _e('No', 'ncstate-branding-bar'); ?></option>
                </select>
            </td>
        </tr>
        <tr valign="top">
            <td width="150">
                <label for="nbb_secure"><?php _e('Use Secure URLs (https)?', 'ncstate-branding-bar'); ?></label>
            </td>
            <td>
                <select id="nbb_secure" name="nbb_secure">
                    <option value="1" <?php selected((int)$options['secure'], 1); ?>><?php _e('Yes', 'ncstate-branding-bar'); ?></option>
                    <option value="0" <?php selected((int)$options['secure'], 0); ?>><?php _e('No', 'ncstate-branding-bar'); ?></option>
                </select>
            </td>
        </tr>
        <tr valign="top">
            <td>
                <label for="nbb_color"><?php _e('Color Choice:', 'ncstate-branding-bar'); ?></label>
            </td>
            <td>
                <select id="nbb_color" name="nbb_color">
                    <?php foreach ($colorOptions as $key => $value): ?>
                    <option value="<?php echo $key; ?>" <?php selected($options['color'], $key); ?>><?php _e($value, 'ncstate-branding-bar'); ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
        <tr valign="top">
            <td>
                <label for="nbb_centered"><?php _e('Center Branding Bar?', 'ncstate-branding-bar'); ?></label>
            </td>
            <td>
                <select id="nbb_centered" name="nbb_centered">
                    <option value="1" <?php selected((int)$options['centered'], 1); ?>><?php _e('Yes', 'ncstate-branding-bar'); ?></option>
                    <option value="0" <?php selected((int)$options['centered'], 0); ?>><?php _e('No', 'ncstate-branding-bar'); ?></option>
                </select>
            </td>
        </tr>
        <tr valign="top">
            <td width="150">
                <label for="nbb_position"><?php _e('Prepend to Element:', 'ncstate-branding-bar'); ?></label>
            </td>
            <td>
                <input type="text" size="20" id="nbb_position" name="nbb_position" value="<?php echo $this->_position; ?>" /><br />
                * Use CSS selectors like &quot;#pageHeader&quot; or &quot;body&quot;
            </td>
        </tr>
        <tr valign="top">
            <td>
                <label for="nbb_siteUrl"><?php _e('Site URL for Searching:', 'ncstate-branding-bar'); ?></label>
            </td>
            <td>
                http://<input type="text" size="40" id="nbb_siteUrl" name="nbb_siteUrl" value="<?php echo $options['siteUrl']; ?>" /><br />
                * Will not work when <b>Secure URLs</b> are enabled.  Make this blank to remove on-site searching from the branding bar
            </td>
        </tr>
        <tr valign="top">
            <td>
                <label for="nbb_noIframePrompt"><?php _e('Prompt for No Iframe:', 'ncstate-branding-bar'); ?></label>
            </td>
            <td>
                <textarea id="nbb_noIframePrompt" name="nbb_noIframePrompt" rows="3" cols="50"><?php echo $options['noIframePrompt']; ?></textarea><br />
                * Will be displayed if the user has disabled iframes
            </td>
        </tr>
        <tr valign="top">
            <td width="150">
                <label for="nbb_responsive"><?php _e('Responsive Brand Bar', 'ncstate-branding-bar'); ?></label>
            </td>
            <td>
                <select id="nbb_responsive" name="nbb_responsive">
                    <option value="1" <?php selected((int)$this->_responsive, 1); ?>><?php _e('Enabled', 'ncstate-branding-bar'); ?></option>
                    <option value="0" <?php selected((int)$this->_responsive, 0); ?>><?php _e('Disabled', 'ncstate-branding-bar'); ?></option>
                </select>
                <br />
                * Disabling will result in the default brand bar attempting to display on smaller resolution displays
            </td>
        </tr>
    </table>


    <p class="submit">
        <input type="hidden" name="action" value="ncstate-branding-bar" />
        <input type="submit" name="Submit" value="<?php _e('Save Changes') ?>" />
    </p>

    </form>
<br /><br />
Uses version <?php echo Ncstate_Version::VERSION; ?> of the 
<a href="https://github.com/ncsuwebdev/PHP-Ncstate">PHP-Ncstate library</a>.
